services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/html
    user: root
    volumes:
      - '${PROJECT_PATH}:/var/www/html'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
    ports:
      - '8000:8000'
  nginx:
    image: 'nginx:1.25'
    container_name: nginx
    ports:
      - '8080:8080'
    volumes:
      - '${PROJECT_PATH}/docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:rw'
      - '${PROJECT_PATH}/docker/conf/nginx/conf.d:/etc/nginx/conf.d:rw'
      - '${PROJECT_PATH}/docker/conf/nginx/html:/usr/share/nginx/html:rw'
      - '${PROJECT_PATH}/docker/conf/nginx/logs:/var/log/nginx:rw'
    restart: unless-stopped
