services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - "./:/var/www/html"
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf:rw'
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
      - './docker/nginx/html:/usr/share/nginx/html:rw'
      - './docker/nginx/logs:/var/log/nginx:rw'
    environment:
      APP_ENV: local
    restart: unless-stopped
